security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    app_user:
      entity:
        class: App\Entity\User
  firewalls:
    main:
      lazy: true
      provider: app_user
      custom_authenticators:
        - App\Security\AppAuthenticator
      logout:
        path: app_logout
