version: '3.3'
services:
  php:
    build:
      context: ./docker/php-fpm
    ports:
      - 9001:9001
    volumes:
      - ./:/application:cached
    depends_on:
      - db

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./:/application:cached

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: { }
